server:
  port: 8090

spring:
  security:
    user:
      name: admin
      password: admin
    enable-csrf: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password

logging:
  level:
    org:
      springframework: debug